# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:59
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0011_bill_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extras',
            field=jsonfield.fields.JSONCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='extras',
            field=jsonfield.fields.JSONCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='extras',
            field=jsonfield.fields.JSONCharField(blank=True, max_length=255),
        ),
    ]
